import type { Metadata } from "next";
import { Header } from "@/components/landing/Header";
import { Footer } from "@/components/landing/Footer";
import { JsonLd } from "@/lib/seo/JsonLd";
import { generateBreadcrumbSchema, generatePageMetadata } from "@/lib/seo/config";
import { OpenPositionsClient } from "./OpenPositionsClient";
export const metadata: Metadata = { ...generatePageMetadata({ title: "Careers enquiries | Whats91", description: "Check the status of previously listed role categories at Whats91. Current openings and employment terms need confirmation before you submit an application.", path: "/careers" }), robots: { index: false, follow: true } };
export default function CareersPage() {
  return <div className="min-h-screen flex flex-col bg-background"><JsonLd data={generateBreadcrumbSchema([{ name: "Home", url: "/" }, { name: "Careers", url: "/careers" }])} /><Header /><main id="main-content" tabIndex={-1} className="flex-1">
    <section className="py-12 sm:py-16 bg-surface/50"><div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-4"><h1 className="text-3xl sm:text-4xl font-bold">Careers enquiries</h1><p className="text-lg text-text-secondary">Current openings have not been confirmed. The role categories below were previously listed and are available for reference.</p><p className="text-text-secondary">Before sending a CV, ask whether a role is accepting applications and confirm its location, work arrangement, requirements, compensation and benefits. No posting date or employment package is advertised here.</p></div></section>
    <section id="positions" aria-labelledby="roles-heading" className="py-12 sm:py-16"><div className="max-w-5xl mx-auto px-4 sm:px-6"><h2 id="roles-heading" className="text-2xl font-semibold text-center mb-4">Previously listed role categories</h2><p className="text-center text-text-secondary mb-8">These labels do not establish an open vacancy.</p><noscript><p className="mb-6 text-sm text-text-secondary">All previously listed categories are shown below. Filters and expandable details need JavaScript; use the availability enquiry link below to ask about a role.</p></noscript><OpenPositionsClient /></div></section>
    <section className="py-12 sm:py-16 bg-surface/50"><div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-4"><h2 className="text-2xl font-semibold">Check before applying</h2><p className="text-text-secondary">The website lists careers@whats91.com for careers enquiries. Its current monitoring and recruiting process need confirmation. Avoid sending sensitive documents until you have confirmed the recipient and application process.</p><a className="inline-flex min-h-11 items-center underline text-brand-primary break-all" href="mailto:careers@whats91.com?subject=Current%20role%20availability%20enquiry">Ask about current role availability</a><p className="text-sm text-text-secondary">This link opens your email application. It does not submit an application or confirm a vacancy.</p></div></section>
  </main><Footer /></div>;
}
