export interface Template {
  id: string;
  name: string;
  category: "marketing" | "utility" | "authentication";
  industry?: string;
  header?: { type: "text" | "image" | "video" | "document"; content: string };
  body: string;
  footer?: string;
  buttons?: { type: "quick_reply" | "url" | "phone" | "copy_code"; text: string; value?: string }[];
  variables: string[];
  useCase: string;
}

export const marketingTemplates: Template[] = [
  {
    id: "m1",
    name: "Welcome New Customer",
    category: "marketing",
    industry: "E-commerce",
    header: { type: "image", content: "Welcome banner image" },
    body: "Hi {{1}}, welcome to {{2}}! Use code WELCOME{{3}} for 15% off your first order!",
    footer: "Reply STOP to unsubscribe",
    buttons: [{ type: "url", text: "Shop Now", value: "https://example.com/shop" }],
    variables: ["Customer Name", "Brand Name", "Discount Code"],
    useCase: "Customer onboarding with first-purchase incentive",
  },
  {
    id: "m2",
    name: "Abandoned Cart Recovery",
    category: "marketing",
    industry: "E-commerce",
    header: { type: "image", content: "Product image" },
    body: "Hi {{1}}, you left {{2}} in your cart! Complete your purchase and get free shipping on orders over {{3}}.",
    footer: "Reply STOP to unsubscribe",
    buttons: [
      { type: "url", text: "Complete Purchase", value: "https://example.com/cart" },
      { type: "quick_reply", text: "Remind Later" },
    ],
    variables: ["Customer Name", "Product Name", "Threshold Amount"],
    useCase: "Recover lost sales from abandoned shopping carts",
  },
  {
    id: "m3",
    name: "Flash Sale Alert",
    category: "marketing",
    industry: "Retail",
    header: { type: "image", content: "Sale banner" },
    body: "FLASH SALE! {{1}}, get {{2}}% off everything for the next {{3}} hours only! Use code: FLASH{{4}}",
    footer: "Terms apply. Reply STOP to opt out.",
    buttons: [{ type: "url", text: "Shop Sale", value: "https://example.com/sale" }],
    variables: ["Customer Name", "Discount %", "Hours Remaining", "Unique Code"],
    useCase: "Time-sensitive promotional campaigns",
  },
  {
    id: "m4",
    name: "New Product Launch",
    category: "marketing",
    industry: "E-commerce",
    header: { type: "video", content: "Product demo video" },
    body: "{{1}}, exciting news! Our new {{2}} is finally here. Be among the first to experience {{3}}. Pre-order now!",
    footer: "Reply STOP to unsubscribe",
    buttons: [
      { type: "url", text: "Learn More", value: "https://example.com/product" },
      { type: "url", text: "Pre-Order", value: "https://example.com/preorder" },
    ],
    variables: ["Customer Name", "Product Name", "Key Feature"],
    useCase: "Product launch announcements",
  },
  {
    id: "m5",
    name: "Seasonal Greeting",
    category: "marketing",
    industry: "All",
    header: { type: "image", content: "Festive image" },
    body: "Happy {{1}} from all of us at {{2}}! As a thank you, enjoy {{3}}% off your next purchase.",
    footer: "Reply STOP to unsubscribe",
    buttons: [{ type: "url", text: "Shop Now", value: "https://example.com/shop" }],
    variables: ["Occasion", "Brand Name", "Discount %"],
    useCase: "Festival and holiday campaigns",
  },
  {
    id: "m6",
    name: "Loyalty Reward",
    category: "marketing",
    industry: "Retail",
    header: { type: "image", content: "Rewards banner" },
    body: "{{1}}, you've earned it! You've collected {{2}} loyalty points. Redeem them for exclusive rewards!",
    footer: "Points expire in 30 days. Reply STOP to opt out.",
    buttons: [
      { type: "url", text: "View Rewards", value: "https://example.com/rewards" },
      { type: "quick_reply", text: "Save Points" },
    ],
    variables: ["Customer Name", "Points Balance"],
    useCase: "Customer retention and loyalty programs",
  },
  {
    id: "m7",
    name: "Re-engagement",
    category: "marketing",
    industry: "All",
    body: "Hi {{1}}, we miss you! It's been a while since your last visit. Here's an exclusive {{2}}% discount. Code: COMEBACK{{3}}",
    footer: "Valid for 7 days. Reply STOP to unsubscribe.",
    buttons: [{ type: "url", text: "Shop Now", value: "https://example.com/shop" }],
    variables: ["Customer Name", "Discount %", "Unique Code"],
    useCase: "Win-back campaigns for inactive customers",
  },
  {
    id: "m8",
    name: "Travel Deal",
    category: "marketing",
    industry: "Travel",
    header: { type: "image", content: "Destination image" },
    body: "{{1}}, escape to {{2}}! Book now and save {{3}}% on your dream vacation. Limited seats from {{4}}.",
    footer: "Terms apply. Reply STOP to unsubscribe.",
    buttons: [
      { type: "url", text: "View Deal", value: "https://example.com/travel" },
      { type: "phone", text: "Call Expert", value: "+1234567890" },
    ],
    variables: ["Customer Name", "Destination", "Discount %", "Starting Price"],
    useCase: "Travel and hospitality promotions",
  },
];

export const utilityTemplates: Template[] = [
  {
    id: "u1",
    name: "Order Confirmation",
    category: "utility",
    industry: "E-commerce",
    body: "Hi {{1}}, your order #{{2}} has been confirmed!\n\nItems: {{3}}\nTotal: {{4}}\nEstimated delivery: {{5}}",
    footer: "Thank you for shopping with us!",
    buttons: [{ type: "url", text: "Track Order", value: "https://example.com/track" }],
    variables: ["Customer Name", "Order ID", "Items", "Total Amount", "Delivery Date"],
    useCase: "Order confirmation notifications",
  },
  {
    id: "u2",
    name: "Shipping Update",
    category: "utility",
    industry: "E-commerce",
    body: "Hi {{1}}, good news! Your order #{{2}} has been shipped via {{3}}. Expected delivery: {{4}}.",
    footer: "Track your package for real-time updates.",
    buttons: [{ type: "url", text: "Track Package", value: "https://example.com/track" }],
    variables: ["Customer Name", "Order ID", "Carrier", "Delivery Date"],
    useCase: "Shipping and delivery notifications",
  },
  {
    id: "u3",
    name: "Delivery Confirmation",
    category: "utility",
    industry: "E-commerce",
    body: "Hi {{1}}, your order #{{2}} has been delivered! We hope you love your purchase.",
    footer: "Reply with any questions about your order.",
    buttons: [
      { type: "url", text: "Write Review", value: "https://example.com/review" },
      { type: "quick_reply", text: "Report Issue" },
    ],
    variables: ["Customer Name", "Order ID"],
    useCase: "Delivery completion notifications",
  },
  {
    id: "u4",
    name: "Appointment Reminder",
    category: "utility",
    industry: "Healthcare",
    body: "Hi {{1}}, reminder of your appointment with {{2}} on {{3}} at {{4}}. Location: {{5}}.",
    footer: "Please arrive 10 minutes early.",
    buttons: [
      { type: "quick_reply", text: "Confirm" },
      { type: "quick_reply", text: "Reschedule" },
      { type: "quick_reply", text: "Cancel" },
    ],
    variables: ["Patient Name", "Doctor/Provider", "Date", "Time", "Location"],
    useCase: "Appointment reminders",
  },
  {
    id: "u5",
    name: "Payment Receipt",
    category: "utility",
    industry: "Finance",
    body: "Hi {{1}}, payment of {{2}} received for invoice #{{3}}. Transaction ID: {{4}}. Date: {{5}}.",
    footer: "Thank you for your payment.",
    buttons: [{ type: "url", text: "Download Receipt", value: "https://example.com/receipt" }],
    variables: ["Customer Name", "Amount", "Invoice Number", "Transaction ID", "Date"],
    useCase: "Payment confirmations",
  },
  {
    id: "u6",
    name: "Bill Reminder",
    category: "utility",
    industry: "Utilities",
    body: "Hi {{1}}, your {{2}} bill of {{3}} is due on {{4}}. Account: {{5}}.",
    footer: "Avoid late fees by paying on time.",
    buttons: [
      { type: "url", text: "Pay Now", value: "https://example.com/pay" },
      { type: "quick_reply", text: "Remind Later" },
    ],
    variables: ["Customer Name", "Bill Type", "Amount", "Due Date", "Account Number"],
    useCase: "Bill payment reminders",
  },
  {
    id: "u7",
    name: "Account Update",
    category: "utility",
    industry: "All",
    body: "Hi {{1}}, your account settings have been updated. {{2}} was changed on {{3}}.",
    footer: "If you didn't make this change, contact us immediately.",
    buttons: [{ type: "url", text: "Review Activity", value: "https://example.com/security" }],
    variables: ["Customer Name", "What Changed", "Date/Time"],
    useCase: "Account security notifications",
  },
  {
    id: "u8",
    name: "Service Status",
    category: "utility",
    industry: "Services",
    body: "Hi {{1}}, your {{2}} service has been {{3}}. Reference: {{4}}. Next steps: {{5}}.",
    footer: "Questions? Reply to this message.",
    buttons: [{ type: "url", text: "View Details", value: "https://example.com/status" }],
    variables: ["Customer Name", "Service Type", "Status", "Reference ID", "Next Steps"],
    useCase: "Service status updates",
  },
];

export const authenticationTemplates: Template[] = [
  {
    id: "a1",
    name: "OTP Verification (Copy Code)",
    category: "authentication",
    body: "{{1}} is your verification code. For your security, do not share this code.",
    buttons: [{ type: "copy_code", text: "Copy Code" }],
    variables: ["OTP Code"],
    useCase: "Standard OTP with copy button",
  },
  {
    id: "a2",
    name: "OTP with Expiry",
    category: "authentication",
    body: "{{1}} is your verification code. This code will expire in {{2}} minutes. For your security, do not share this code.",
    buttons: [{ type: "copy_code", text: "Copy Code" }],
    variables: ["OTP Code", "Expiry Minutes"],
    useCase: "OTP with expiration warning",
  },
  {
    id: "a3",
    name: "Login Verification",
    category: "authentication",
    body: "Your login verification code is {{1}}. If you didn't request this code, someone may be trying to access your account.",
    buttons: [{ type: "copy_code", text: "Copy Code" }],
    variables: ["OTP Code"],
    useCase: "Two-factor authentication for login",
  },
  {
    id: "a4",
    name: "Transaction Verification",
    category: "authentication",
    body: "{{1}} is your verification code to authorize transaction #{{2}}. For your security, do not share this code.",
    buttons: [{ type: "copy_code", text: "Copy Code" }],
    variables: ["OTP Code", "Transaction ID"],
    useCase: "High-value transaction authorization",
  },
];

