"use client";

import { useId, useState } from "react";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { metaPricingSchedule, metaPricingQualification, categoryLabels, budgetCategories, metaCategories, estimateScheduledMetaCost, getMetaMarket, formatMetaMoney, formatMetaRate, metaTierRows, servicePricingPolicy, utilityPricingPolicy, freeEntryPricingPolicy, tierPricingPolicy, internationalPricingPolicy, type BudgetCounts } from "@/lib/meta-pricing";

const zero = { marketing: "0", utility: "0", authentication: "0", service: "0" };
const selectClass = "h-11 w-full rounded-md border border-border bg-background px-3 text-sm";

/** Both entry points use the same dated card and financial rules; no account is accessed. */
export function MessageBudget() {
  const id = useId();
  const [marketId, setMarket] = useState("IN");
  const [month, setMonth] = useState(metaPricingSchedule.effectiveFrom.slice(0, 7));
  const [volumes, setVolumes] = useState<BudgetCounts>({ ...zero, marketing: "1000", utility: "1000" });
  const [freeEntry, setFreeEntry] = useState<BudgetCounts>(zero);
  const [allowance, setAllowance] = useState(String(metaPricingSchedule.serviceFreePerPhonePerMonth));
  const [priorUtility, setPriorUtility] = useState("0");
  const [priorAuthentication, setPriorAuthentication] = useState("0");
  const [mode, setMode] = useState<"domestic" | "international">("domestic");
  const [internationalEligible, setInternationalEligible] = useState(false);
  const market = getMetaMarket(marketId)!;
  const estimate = estimateScheduledMetaCost({ market: marketId, currency: metaPricingSchedule.currency, date: `${month}-01`, volumes, freeEntry, serviceAllowanceRemaining: allowance, priorUtility, priorAuthentication, authenticationMode: mode, internationalEligible });
  const amount = (value: number | null) => value === null ? "Unavailable" : formatMetaMoney(value);
  return (
    <div className="space-y-6" data-testid="message-budget">
      <p id={`${id}-qualification`} className="rounded-xl border border-info-border bg-info-soft p-4 text-sm text-text-secondary">{metaPricingQualification}</p>
      <p className="text-caption">The initial scenario is 1,000 Marketing and 1,000 Utility deliveries to India in October 2026, with no prior paid tier volume. Edit counts for your budget. This is a Meta subtotal, not an invoice or total payable.</p>
      <noscript><p className="text-caption">The initial scenario, rates and policies below are readable without JavaScript. Changing the estimate requires JavaScript.</p></noscript>
      <div className="surface-card p-5 sm:p-8 space-y-6">
        <div className="grid gap-6 sm:grid-cols-2">
          <div><Label htmlFor={`${id}-market`} className="block mb-2">Recipient market · INR billing</Label><select id={`${id}-market`} value={marketId} onChange={event => setMarket(event.target.value)} className={selectClass}>{metaPricingSchedule.markets.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><p className="text-caption mt-2">Use the recipient market, not your business location. All amounts use the original INR card; no currency conversion.</p></div>
          <div><Label htmlFor={`${id}-month`} className="block mb-2">Delivery month</Label><Input id={`${id}-month`} type="month" min={metaPricingSchedule.effectiveFrom.slice(0, 7)} value={month} onChange={event => setMonth(event.target.value)} className="h-11" /><p className="text-caption mt-2">One monthly period in the Messaging account timezone. The manually maintained schedule starts on 1 October 2026.</p></div>
          {budgetCategories.map(key => <div key={key}><Label htmlFor={`${id}-${key}`} className="block mb-2">{categoryLabels[key]} delivered messages</Label><Input id={`${id}-${key}`} type="text" inputMode="numeric" value={volumes[key]} onChange={event => setVolumes(previous => ({ ...previous, [key]: event.target.value }))} aria-describedby={`${id}-count-help`} className="h-11" /></div>)}
        </div>
        <p id={`${id}-count-help`} className="text-caption">Whole counts from 0 to 1,000,000,000. Count delivered recipients, including each group recipient. Include confirmed free-entry deliveries in these category counts; exclude failed, incoming and unresolved sends.</p>
        <div><Label htmlFor={`${id}-auth-mode`} className="block mb-2">Authentication treatment for this cohort</Label><select id={`${id}-auth-mode`} className={selectClass} value={mode} onChange={event => setMode(event.target.value as "domestic" | "international")}><option value="domestic">Domestic authentication</option><option value="international">Authentication international — confirmed eligible account</option></select><p className="text-caption mt-2">{internationalPricingPolicy} For mixed domestic/international traffic, calculate cohorts in delivery order using their shared prior Authentication count.</p>{mode === "international" && <label className="flex min-h-11 items-start gap-3 mt-3 text-sm"><input type="checkbox" className="mt-1 h-5 w-5 accent-primary" checked={internationalEligible} onChange={event => setInternationalEligible(event.target.checked)} />I have confirmed Meta eligibility, primary business location and the applicable account start date/notice.</label>}</div>
        <div><Label htmlFor={`${id}-allowance`} className="block mb-2">Service free allowance remaining for this business phone number</Label><Input id={`${id}-allowance`} type="text" inputMode="numeric" value={allowance} onChange={event => setAllowance(event.target.value)} className="h-11" /><p className="text-caption mt-2">0–{metaPricingSchedule.serviceFreePerPhonePerMonth.toLocaleString("en-IN")}. Default assumes the full monthly allowance remains on one phone number. Subtract Service allowance already used across all markets, accounts and 1:1/group traffic. Estimate additional phone numbers separately.</p></div>
        <details className="rounded-xl border border-border p-4"><summary className="min-h-11 cursor-pointer font-semibold">Free-entry exclusions and prior monthly tier counts</summary><p className="text-body-sm mt-2">Enter only deliveries confirmed inside Meta’s eligible free-entry window. Default is zero; the calculator cannot inspect eligibility or expiry. Each excluded count must be within the corresponding delivered count.</p><div className="grid gap-4 sm:grid-cols-2 mt-4">{budgetCategories.map(key => <div key={key}><Label htmlFor={`${id}-free-${key}`} className="block mb-2">{categoryLabels[key]} free-entry deliveries included above</Label><Input id={`${id}-free-${key}`} type="text" inputMode="numeric" value={freeEntry[key]} onChange={event => setFreeEntry(previous => ({ ...previous, [key]: event.target.value }))} className="h-11" /></div>)}<div><Label htmlFor={`${id}-prior-utility`} className="block mb-2">Earlier paid Utility deliveries this month · portfolio/market</Label><Input id={`${id}-prior-utility`} type="text" inputMode="numeric" value={priorUtility} onChange={event => setPriorUtility(event.target.value)} className="h-11" /></div><div><Label htmlFor={`${id}-prior-auth`} className="block mb-2">Earlier paid Authentication deliveries · includes international</Label><Input id={`${id}-prior-auth`} type="text" inputMode="numeric" value={priorAuthentication} onChange={event => setPriorAuthentication(event.target.value)} className="h-11" /></div></div><p className="text-caption mt-3">Prior counts default to zero for a new monthly cohort. Include paid deliveries across the business portfolio’s messaging accounts for this market/category. Free-entry deliveries do not advance these counts.</p></details>
        <p role="status" aria-live="polite" aria-atomic="true" className="text-sm font-medium">{estimate.status === "estimate" ? `Estimated Meta delivery subtotal: ${amount(estimate.meta)}. Service allowance applied: ${estimate.serviceFree.toLocaleString("en-IN")} deliveries.` : `Estimate unavailable: ${estimate.reason}`}</p>
        <dl className="space-y-3 border-t border-border pt-4 text-sm">{estimate.status === "estimate" && budgetCategories.map(key => <div key={key} className="flex flex-wrap justify-between gap-2"><dt>{categoryLabels[key]} · {estimate.billable[key].toLocaleString("en-IN")} billable</dt><dd>{amount(estimate.categories[key])}</dd></div>)}{[["Meta delivery subtotal · no Whats91 markup", amount(estimate.meta)], ["Whats91 platform and setup", "Listed on Plans page"], ["GST and other taxes", "Plan GST calculated separately"], ["Total payable", "Unavailable until all components are quoted"]].map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2"><dt>{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl>
        <Link href="/plans" className="inline-flex min-h-11 items-center text-primary underline">Compare Whats91 platform prices and setup</Link>
        <p className="text-caption">The Meta subtotal rounds once to two decimals after all category calculations at original rate precision. Rounded category displays can differ from their summed subtotal by a paisa. Calling and Marketing Messages API token charges are outside this estimate.</p>
      </div>
      <section aria-labelledby={`${id}-rules`} className="surface-card p-5 sm:p-8 space-y-4"><h3 id={`${id}-rules`} className="text-lg font-semibold">Allowances, windows and tiers</h3>{[servicePricingPolicy, utilityPricingPolicy, freeEntryPricingPolicy, tierPricingPolicy].map(text => <p className="text-body-sm" key={text}>{text}</p>)}</section>
      <section aria-labelledby={`${id}-tiers`} className="surface-card p-5 sm:p-8"><h3 id={`${id}-tiers`} className="text-lg font-semibold">{market.name} marginal tiers · INR · {metaPricingSchedule.effectiveLabel}</h3><div role="region" aria-labelledby={`${id}-tiers`} tabIndex={0} className="overflow-x-auto mt-4"><table className="w-full min-w-[580px] text-left text-sm"><caption className="sr-only">Monthly paid volume tiers for the selected market</caption><thead><tr>{["Category", "Monthly tier", "Rate per delivery"].map(label => <th key={label} scope="col" className="p-3">{label}</th>)}</tr></thead><tbody>{metaTierRows(market).map(row => <tr key={row.join("-")} className="border-t border-border">{row.map((value, index) => index === 0 ? <th key={index} scope="row" className="p-3 font-medium">{value}</th> : <td key={index} className="p-3">{value}</td>)}</tr>)}</tbody></table></div></section>
      <section aria-labelledby={`${id}-rates`} className="surface-card p-5 sm:p-8"><h3 id={`${id}-rates`} className="text-lg font-semibold">All recipient markets · INR list rates · {metaPricingSchedule.effectiveLabel}</h3><p className="text-caption my-3">Per delivered message, before tier discounts and eligible exclusions. Authentication international N/A means no listed rate; it is not free.</p><div role="region" aria-labelledby={`${id}-rates`} tabIndex={0} className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[900px] text-left text-sm"><caption className="sr-only">Official INR billing card, 47 recipient markets and regions</caption><thead><tr>{["Recipient market", ...metaCategories.map(key => categoryLabels[key])].map(label => <th key={label} scope="col" className="p-3">{label}</th>)}</tr></thead><tbody>{metaPricingSchedule.markets.map(m => <tr key={m.id} className="border-t border-border"><th scope="row" className="p-3 font-medium">{m.name}</th>{metaCategories.map(key => <td key={key} className="p-3 whitespace-nowrap">{formatMetaRate(m.rates[key])}</td>)}</tr>)}</tbody></table></div><a href={metaPricingSchedule.source} className="inline-flex min-h-11 items-center text-primary underline mt-3">Meta’s effective rate cards and policy</a></section>
    </div>
  );
}
