import Link from "next/link";
import type { Metadata } from "next";
import { Header } from "@/components/landing/Header";
import { Footer } from "@/components/landing/Footer";
import { BookDemoPopup } from "@/components/landing/BookDemoPopup";
import { JsonLd } from "@/lib/seo/JsonLd";
import { generateBreadcrumbSchema, generatePageMetadata } from "@/lib/seo/config";
export const metadata: Metadata = generatePageMetadata({ title: "About Whats91 | Messaging and ERP workflows", description: "Understand the Whats91 website's focus on WhatsApp Cloud API messaging, ERP connections and automation, and find the right enquiry and policy pages.", path: "/about" });
export default function AboutPage() {
  return <div className="min-h-screen flex flex-col bg-background"><JsonLd data={generateBreadcrumbSchema([{ name: "Home", url: "/" }, { name: "About", url: "/about" }])} /><Header />
    <main id="main-content" tabIndex={-1} className="flex-1">
      <section className="py-12 sm:py-16 bg-surface/50"><div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-5"><h1 className="text-3xl sm:text-4xl font-bold">About Whats91</h1><p className="text-lg text-text-secondary">This website explains WhatsApp Cloud API messaging, ERP connections and automation workflows for businesses.</p><p className="text-text-secondary">Use the workflow pages to identify what you need. Confirm supported software, enabled account features, implementation responsibilities and written commercial terms before choosing an integration.</p><BookDemoPopup source="about-hero" triggerLabel="Request a demo" /></div></section>
      <section className="py-12 sm:py-16"><div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-6"><h2 className="text-2xl font-semibold">Start with your business workflow</h2><div className="grid sm:grid-cols-2 gap-6">{[{ href: "/solutions/busy-erp", title: "ERP messaging", text: "Explore documents, recipients and sender setup for an ERP messaging workflow." }, { href: "/flow-builder", title: "Automation", text: "Define triggers, data access, permitted actions and human handoff." }].map(item => <article key={item.href} className="rounded-2xl border border-border/60 p-6 space-y-3"><h3 className="text-lg font-semibold">{item.title}</h3><p className="text-sm text-text-secondary">{item.text}</p><Link href={item.href} className="inline-flex min-h-11 items-center underline text-brand-primary">Read the workflow</Link></article>)}</div></div></section>
      <section className="py-12 sm:py-16 bg-surface/50"><div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-4"><h2 className="text-2xl font-semibold">Organization and contact information</h2><p className="text-text-secondary">The website currently identifies its operator as Wilford Technology. Confirm the contracting entity and office arrangements in your written proposal before signing or visiting.</p><p className="text-text-secondary">Company history, leadership profiles and scale figures are not presented here while their details are being checked.</p><Link href="/contact" className="inline-flex min-h-11 items-center underline text-brand-primary">View the listed contact channels</Link><p><Link href="/legal" className="inline-flex min-h-11 items-center underline text-brand-primary">Read policy and document status</Link></p></div></section>
    </main><Footer /></div>;
}
