import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { createManifest,treeFiles,verifyPackage,verifyNamedReleaseDirectory,assertExact,hash } from '../scripts/release/candidate.mjs';
import { offlineStore } from '../scripts/release/offline-store.mjs';
import { rehearseRelease } from '../scripts/release/rehearse.mjs';
import { packageStandalone } from '../scripts/package-standalone.mjs';

function write(root,p,value){const f=path.join(root,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,value);}
function candidate(root,id){const sourceRoot=path.join(root,id+'-source'),runtimeRoot=path.join(root,id+'-runtime');for(const [p,v]of Object.entries({'package.json':'{}','package-lock.json':'{"lockfileVersion":3}','src/lib/graph-form-submissions.ts':'fixture','next.config.ts':'fixture','version.txt':'1.6.3'}))write(sourceRoot,p,v);for(const [p,v]of Object.entries({'start.mjs':'fixture','server.js':'fixture','.next/BUILD_ID':id,'.next/server/app-paths-manifest.json':'{}','.next/static/chunk.js':id,'public/logo.svg':'fixture','version.txt':'1.6.3','node_modules/next/package.json':'{"version":"16.3.6"}'}))write(runtimeRoot,p,v);for(let i=0;i<11;i++)write(runtimeRoot,'src/lib/flows/json/'+i+'.json','{}');const m=createManifest({head:'a'.repeat(40),buildId:id,version:'1.6.3',sourceFiles:treeFiles(sourceRoot),artifacts:treeFiles(runtimeRoot)});write(runtimeRoot,'release-manifest.json',JSON.stringify(m));write(runtimeRoot,'release-identity.json',JSON.stringify({candidateId:m.candidateId,buildId:m.buildId,version:m.version}));return{m,sourceRoot,runtimeRoot};}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'whats91-b28-release-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const token=crypto.randomBytes(16).toString('hex'),storeRoot=path.join(root,'store');fs.mkdirSync(storeRoot);write(storeRoot,'.offline-fixture',token);const old=candidate(root,'old-fixture'),next=candidate(root,'new-fixture'),store=offlineStore(storeRoot,token);store.seed(old.m,old);const calls=[],config={mode:'offline',service:'fixture-whats91',operationMs:100,abortGraceMs:10,notificationMs:20,contentSha256:hash('new-content'),previousContentSha256:hash('old-content')};const ports={store,processKind:'mock',networkKind:'mock',run:async args=>{calls.push({command:args.command,args:args.args,candidateId:args.candidate?.candidateId});return{exitCode:0};},health:async({candidate:m})=>({status:200,readiness:{status:'ready',scope:'website',candidateId:m.candidateId,buildId:m.buildId,version:m.version},version:{version:m.version},contentSha256:m.candidateId===old.m.candidateId?config.previousContentSha256:config.contentSha256})};return{root,storeRoot,old,next,store,calls,config,ports};}
const invoke=f=>rehearseRelease(f.next.m,f.next.m,f.next,f.config,f.ports);

test('a release starts only from a directory named for its verified candidate',t=>{
 const f=fixture(t),named=path.join(f.root,f.next.m.candidateId);
 assert.throws(()=>verifyNamedReleaseDirectory(f.next.runtimeRoot,f.next.m),/RELEASE_DIRECTORY_ID_MISMATCH/);
 fs.cpSync(f.next.runtimeRoot,named,{recursive:true});
 verifyNamedReleaseDirectory(named,f.next.m);
 verifyPackage(named,f.next.m);
});

test('exact dirty source identity and artifact identity both bind the candidate; HEAD alone cannot match',t=>{const f=fixture(t);assertExact(f.next.m,f.next.m);assert.throws(()=>assertExact(f.next.m,{...f.next.m,sourceDigest:f.old.m.sourceDigest+'a'}),/EXACT/);write(f.next.sourceRoot,'src/lib/graph-form-submissions.ts','changed dirty source');assert.throws(()=>f.store.stage(f.next.m,f.next),/MISMATCH/);write(f.next.runtimeRoot,'server.js','changed output');assert.throws(()=>verifyPackage(f.next.runtimeRoot,f.next.m),/MISMATCH/);assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

test('successful offline preparation uses locked install, exact artifact switch and only named restart; replay does not restart',async t=>{const f=fixture(t),r=await invoke(f);assert.equal(r.status,'verified');assert.equal(r.notification,'disabled');assert.equal(f.store.pointers().previous.candidateId,f.old.m.candidateId);assert.deepEqual(f.calls.map(c=>[c.command,c.args]),[['npm',['ci','--ignore-scripts']],['npm',['run','build']],['pm2',['restart','fixture-whats91','--update-env']]]);const count=f.calls.length;assert.equal((await invoke(f)).status,'replayed');assert.equal(f.calls.length,count);assert.ok(!fs.existsSync(path.join(f.storeRoot,'lock')));verifyPackage(path.join(f.storeRoot,'releases',f.old.m.candidateId,'runtime'),f.old.m);});

test('simultaneous and stale locks fail closed without stealing or deleting another owner',async t=>{const f=fixture(t);f.store.acquire('other-owner');await assert.rejects(invoke(f),/LOCK_HELD/);write(f.storeRoot,'lock/owner.json',JSON.stringify({owner:'other-owner',createdAt:0}));await assert.rejects(invoke(f),/LOCK_HELD/);assert.throws(()=>f.store.release('wrong-owner'),/LOCK_NOT_OWNED/);assert.equal(f.store.lockInfo().createdAt,0);assert.equal(f.calls.length,0);f.store.release('other-owner');});

test('concurrent invocations run only one pipeline',async t=>{const f=fixture(t);let unblock;const held=new Promise(r=>unblock=r),original=f.ports.run;f.ports.run=async args=>{if(args.command==='npm')await held;return original(args);};const first=invoke(f);await new Promise(r=>setTimeout(r,10));await assert.rejects(invoke(f),/LOCK_HELD/);unblock();assert.equal((await first).status,'verified');assert.equal(f.calls.filter(c=>c.command==='pm2').length,1);});

for(const phase of ['copy','install','build','verify','start','health'])test(`${phase} failure preserves or recovers exact previous candidate with bounded safe failure`,async t=>{const f=fixture(t);if(phase==='copy')f.ports.store={...f.store,stage:()=>{throw new Error('secret-copy-detail');}};if(['install','build','start'].includes(phase)){const run=f.ports.run;f.ports.run=async a=>{if(phase==='install'&&a.command==='npm'&&a.args[0]==='ci'||phase==='build'&&a.command==='npm'&&a.args[0]==='run'||phase==='start'&&a.candidate?.candidateId===f.next.m.candidateId&&a.command==='pm2')return{exitCode:1};return run(a);};}if(phase==='verify'){const run=f.ports.run;f.ports.run=async a=>{if(a.args[0]==='run'){for(const dir of fs.readdirSync(path.join(f.storeRoot,'staging')))write(path.join(f.storeRoot,'staging',dir),'runtime/server.js','tampered');}return run(a);};}if(phase==='health'){const health=f.ports.health;f.ports.health=async a=>a.candidate.candidateId===f.next.m.candidateId?{status:200,readiness:{status:'ready',candidateId:'wrong'}}:health(a);}const r=await invoke(f);assert.equal(r.status,'failed');assert.equal(r.phase,phase);assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);assert.equal(r.lockHeld,false);assert.equal(r.recovery,['start','health'].includes(phase)?'previous-restored-and-verified-mock':'previous-preserved');assert.ok(!JSON.stringify(r).includes('secret-copy-detail'));verifyPackage(path.join(f.storeRoot,'releases',f.old.m.candidateId,'runtime'),f.old.m);});

test('stalled command holds lock until manual reconciliation; previous remains intact and no switch',async t=>{const f=fixture(t);f.config.operationMs=10;f.ports.run=()=>new Promise(()=>{});const r=await invoke(f);assert.equal(r.status,'failed');assert.equal(r.lockHeld,true);assert.equal(r.recovery,'previous-preserved');assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);await assert.rejects(invoke(f),/LOCK_HELD/);});

test('abort-confirmed process timeout permits safe unlock and recovery',async t=>{const f=fixture(t);f.config.operationMs=10;f.ports.run=({signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new Error('killed fixture')),{once:true}));const r=await invoke(f);assert.equal(r.status,'failed');assert.equal(r.lockHeld,false);assert.ok(!fs.existsSync(path.join(f.storeRoot,'lock')));});

test('failed recovery remains observable and retains lock; no success receipt',async t=>{const f=fixture(t);f.ports.health=async()=>({status:503});const r=await invoke(f);assert.equal(r.status,'failed');assert.equal(r.recovery,'recovery-failed');assert.equal(r.lockHeld,true);assert.equal(f.store.receipt(f.next.m.candidateId),null);assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

test('interrupted switch can replay-check exact healthy candidate without rerunning commands',async t=>{const f=fixture(t);const stage=f.store.stage(f.next.m,f.next);f.store.publish(stage,f.next.m);f.store.switch({current:f.next.m,previous:f.old.m});assert.equal((await invoke(f)).status,'replayed');assert.equal(f.calls.length,0);});

test('unhealthy interrupted switch recovers previous exact candidate; historical replay cannot roll back a later candidate',async t=>{const f=fixture(t);const stage=f.store.stage(f.next.m,f.next);f.store.publish(stage,f.next.m);f.store.switch({current:f.next.m,previous:f.old.m});const health=f.ports.health;f.ports.health=async a=>a.candidate.candidateId===f.next.m.candidateId?{status:503}:health(a);assert.equal((await invoke(f)).recovery,'previous-restored-and-verified-mock');f.store.record(f.next.m.candidateId,{status:'verified'});const r=await invoke(f);assert.equal(r.code,'REPLAY_NOT_CURRENT');assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

test('notification stall is independently bounded and cannot change verified result or expose payload values',async t=>{const f=fixture(t);let payload;f.ports.notify=async p=>{payload=p;return new Promise(()=>{});};const r=await invoke(f);assert.equal(r.status,'verified');assert.equal(r.notification,'mock-failed-or-timeout');assert.deepEqual(Object.keys(payload).sort(),['candidateId','signal','status']);assert.equal(r.lockHeld,false);});

test('live/default ports and unnamed service are refused before any action',async t=>{const f=fixture(t);await assert.rejects(rehearseRelease(f.next.m,f.next.m,f.next,{...f.config,mode:'apply'},f.ports),/OFFLINE_PORTS/);await assert.rejects(rehearseRelease(f.next.m,f.next.m,f.next,{...f.config,service:'all'},f.ports),/NAMED_SERVICE/);assert.equal(f.calls.length,0);});

test('missing package artifacts and private/symlink artifacts fail before promotion',t=>{const f=fixture(t);fs.unlinkSync(path.join(f.next.runtimeRoot,'server.js'));assert.throws(()=>verifyPackage(f.next.runtimeRoot,f.next.m));write(f.next.runtimeRoot,'.env','SYNTHETIC-NOT-A-SECRET');assert.throws(()=>treeFiles(f.next.runtimeRoot),/UNSAFE/);fs.unlinkSync(path.join(f.next.runtimeRoot,'.env'));fs.symlinkSync(f.next.sourceRoot,path.join(f.next.runtimeRoot,'linked'));assert.throws(()=>treeFiles(f.next.runtimeRoot),/SYMLINK/);assert.throws(()=>packageStandalone(path.join(f.root,'missing')),/MISSING_BUILD/);assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

function packaging(t){const f=fixture(t),root=f.next.sourceRoot;write(root,'public/logo.svg','public-fixture');write(root,'scripts/start-standalone.mjs',fs.readFileSync('scripts/start-standalone.mjs'));write(root,'scripts/release/candidate.mjs',fs.readFileSync('scripts/release/candidate.mjs'));for(let i=0;i<11;i++)write(root,'src/lib/flows/json/'+i+'.json','{}');const sources={files:treeFiles(root),excluded:[]};fs.cpSync(f.next.runtimeRoot,path.join(root,'.next/standalone'),{recursive:true});write(root,'.next/BUILD_ID',f.next.m.buildId);write(root,'.next/server/app-paths-manifest.json','{}');write(root,'.next/static/chunk.js',f.next.m.buildId);write(root,'.next/build-source-receipt.json',JSON.stringify({head:f.next.m.head,runtimeFiles:sources.files}));return{...f,packageRoot:root,sources};}

test('standalone packaging binds source-before-build, all runtime/dependency bytes, static/public/11 flow/version and both build IDs',t=>{const f=packaging(t),m=packageStandalone(f.packageRoot,{sources:f.sources,head:f.next.m.head});assert.equal(m.buildId,f.next.m.buildId);verifyPackage(path.join(f.packageRoot,'.next/standalone'),m);assert.ok(m.artifacts['build-source-receipt.json']);assert.ok(m.artifacts['node_modules/next/package.json']);assert.equal(Object.keys(m.artifacts).filter(p=>p.startsWith('src/lib/flows/json/')).length,11);});
for(const broken of ['static','public','flow','version','build-id','source'])test(`standalone ${broken} omission/mismatch fails closed`,t=>{const f=packaging(t);if(broken==='static')fs.rmSync(path.join(f.packageRoot,'.next/static'),{recursive:true});if(broken==='public')fs.rmSync(path.join(f.packageRoot,'public'),{recursive:true});if(broken==='flow')fs.unlinkSync(path.join(f.packageRoot,'.next/standalone/src/lib/flows/json/0.json'));if(broken==='version')fs.unlinkSync(path.join(f.packageRoot,'.next/standalone/version.txt'));if(broken==='build-id')write(f.packageRoot,'.next/standalone/.next/BUILD_ID','wrong');if(broken==='source')write(f.packageRoot,'src/lib/graph-form-submissions.ts','edited since build');assert.throws(()=>packageStandalone(f.packageRoot,{sources:f.sources,head:f.next.m.head}));assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

test('mutable optimizer cache is excluded from immutable runtime and never copied into offline release',t=>{const f=fixture(t);write(f.next.runtimeRoot,'.next/cache/synthetic-image','mutable-cache');verifyPackage(f.next.runtimeRoot,f.next.m);const staged=f.store.stage(f.next.m,f.next);assert.equal(fs.existsSync(path.join(staged.runtime,'.next/cache')),false);});

test('altered embedded manifest fails without relabelling output',t=>{const f=fixture(t);write(f.next.runtimeRoot,'release-manifest.json',JSON.stringify({...f.next.m,buildId:'different'}));assert.throws(()=>verifyPackage(f.next.runtimeRoot,f.next.m),/IDENTITY/);});
for(const wrong of ['build','version','content'])test(`health ${wrong} identity mismatch triggers bounded previous-candidate recovery`,async t=>{const f=fixture(t),health=f.ports.health;f.ports.health=async a=>{const r=await health(a);if(a.candidate.candidateId===f.next.m.candidateId){if(wrong==='build')r.readiness.buildId='wrong';if(wrong==='version')r.version.version='0.0.0';if(wrong==='content')r.contentSha256=hash('wrong');}return r;};const result=await invoke(f);assert.equal(result.status,'failed');assert.equal(result.recovery,'previous-restored-and-verified-mock');assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);});

test('lockfile mutation during mocked preparation prevents the switch',async t=>{const f=fixture(t),run=f.ports.run;f.ports.run=async a=>{if(a.command==='npm'&&a.args[0]==='run')write(a.cwd,'package-lock.json','changed lock');return run(a);};const r=await invoke(f);assert.equal(r.phase,'verify');assert.equal(r.status,'failed');assert.equal(f.store.pointers().current.candidateId,f.old.m.candidateId);assert.equal(f.calls.filter(c=>c.command==='pm2').length,0);});
