import { metaPricingSchedule, indiaRateRows, noMarkupPolicy, servicePricingPolicy, utilityPricingPolicy, freeEntryPricingPolicy, internationalPricingPolicy, tierPricingPolicy } from "@/lib/meta-pricing";
import type { ERPGuide } from "./erp-guides";
import { pricingQualification, commercialQualification, pricingFAQs, metaPricingUrl } from "@/lib/pricing";
import { compatibilityQualification, throughputQualification, historyQualification, migrationQualification, onboardingQualification, windowQualification, entryQualification, organizationQualification, compatibilityRows } from "@/lib/platform-compatibility";

export type BillingGuide = ERPGuide & { faqId?: string; relatedId?: string };
export const billingEvidenceDate = "29 September 2026";
export const messagingPolicyURL = "https://whatsappbusiness.com/policy/";
export const platformOverviewURL = "https://whatsappbusiness.com/products/business-platform/";
export const migrationHistoryURL = "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2197146&lang=1&reg=3";
const priceLink = { label: `Meta pricing — documentation checked ${billingEvidenceDate}`, href: metaPricingUrl };
const policyLink = { label: `Business Messaging Policy — checked ${billingEvidenceDate}; policy dated 23 September 2026`, href: messagingPolicyURL };
const planners = [{ label: "Pricing and message-volume planner", href: "/pricing#calculator" }, { label: "Free message-volume planner", href: "/tools/whatsapp-api-cost-calculator" }, { label: "Platform selection conditions", href: "/plans" }];
const accountTable = { caption: "Standard and hybrid planning comparison", headers: ["Aspect", "Standard Cloud API", "Hybrid Coexistence"], rows: compatibilityRows.map(row => [row.feature, row.standard, row.hybrid]) };
const billingParagraphs = [pricingQualification, "Meta’s public pricing page, checked 29 September 2026, describes charges for delivered messages by recipient market and category. Keep an API acknowledgement, delivery evidence and an invoice as separate records. A queued or accepted request is not a final charge; missing evidence leaves billing unresolved.", commercialQualification];

export const syntheticBillingRows = [
  ["Marketing", "11,000", "₹0.20, one invented rate", "₹2,200.00"],
  ["Utility", "1,200", "First 1,000 × ₹0.10; next 200 × ₹0.08", "₹116.00"],
  ["Authentication", "1,010", "First 1,000 × ₹0.05; next 10 × ₹0.04", "₹50.40"],
  ["Service", "4,000", "₹0.00 only by this fixture’s explicit assumption", "₹0.00"],
] as const;
export const syntheticBillingCode = "Synthetic INR exercise — not a rate card or quote\nMarketing: 11000 × 0.20 = 2200.00\nUtility: 1000 × 0.10 + 200 × 0.08 = 116.00\nAuthentication: 1000 × 0.05 + 10 × 0.04 = 50.40\nMeta-model subtotal: 2200.00 + 116.00 + 50.40 = 2366.40\nPlatform, setup and tax: unavailable; total payable: unavailable";

export const cloudGuide: BillingGuide = {
  slug: "whatsapp-cloud-api-complete-guide-2026",
  cover: { src: "/images/blog/whatsapp-cloud-api-complete-guide-2026/cover-refined-v2-2026-10-watermarked.webp", width: 1200, height: 676, alt: "Illustrated message card linked to a business record and a human reviewer by a green path", caption: "Illustration: messaging, business records and human review are distinct parts of a planned workflow." },
  title: "WhatsApp Cloud API: Setup, Delivery and Billing Guide",
  description: "Plan a WhatsApp Cloud API setup with account checks, delivery reconciliation, billing conditions and a measured pilot before connecting business workflows.",
  intro: "Cloud API is an API path for business messaging. A useful implementation needs more than a successful send: assess the number, choose an interface, handle incoming messages and delivery updates, reconcile costs and give customers a clear route to a person. This guide takes those decisions in order.",
  sections: [
    { id: "guide-platform-conditions", heading: "Choose the registration path before changing the number", paragraphs: [migrationQualification, compatibilityQualification, historyQualification, "List whether staff currently answer on the Business App, use an API inbox or rely on a browser-linked integration. Record who controls the number and business portfolio. Those facts determine what must be assessed; a plan label does not establish eligibility, a complete history transfer or a badge."], table: accountTable, links: [{ label: "Standard and hybrid account assessment", href: "/whatsapp-coexistence" }] },
    { id: "cloud-operating-model", heading: "Separate the API from your business interface", image: { src: "/images/blog/whatsapp-cloud-api-complete-guide-2026/operating-model-refined-2026-10-watermarked.webp", width: 1440, height: 810, alt: "Illustrated messaging cloud, business record folder and human operator reviewing an unresolved message", caption: "Illustration: messaging access, application records and human review are separate responsibilities; unresolved cases need an operator path." }, paragraphs: ["Think of the implementation as three cooperating parts: messaging access, your application and the people operating the workflow. The API carries messages and status events; your application supplies customer mapping, approvals, records and the inbox or automation your team needs.", "Meta’s platform overview describes business messaging APIs; it does not establish which Whats91 plan includes an inbox, chatbot, ERP connector or analytics dashboard. Compare the actual service scope rather than treating every implementation provider as interchangeable.", "For an invoice workflow, obtain the final document and permitted recipient from your business system, then record the message reference and subsequent outcome. For customer support, define who receives an incoming enquiry and how an unresolved automation reaches a person. These are design examples, not proof of an already connected ERP."], links: [{ label: `Meta platform overview — checked ${billingEvidenceDate}`, href: platformOverviewURL }], table: { caption: "Implementation responsibilities to agree", headers: ["Area", "Direct implementation", "Provider-assisted implementation"], rows: [["Application and inbox", "Choose/build and operate your interface", "Confirm interface, permissions and included features"], ["ERP/customer mapping", "Design and verify each integration", "Confirm supported connector and data scope"], ["Webhook and recovery", "Own endpoint, monitoring and failures", "Agree responsibilities and escalation"], ["Support and launch", "Assign operators and readiness checks", "Agree service scope and schedule"]] } },
    { id: "cloud-setup", heading: "Prepare access, identity and a safe setup", paragraphs: ["Use a real business identity and the permissions required by the selected onboarding flow. Collect genuine details first and check whether verification is requested for that portfolio. A universal document checklist or fixed approval time would obscure account-specific requirements.", onboardingQualification, "If a selected flow asks for a website or supporting documents, submit genuine material describing your business and resolve inconsistencies. Do not use a dummy website to get through a review. The messaging policy calls for accurate business information and a support contact; its contact options are not a universal website-verification checklist.", "The following is a reading checklist, not an account checker. Completing it here does not submit documents, verify a business or grant API access."], steps: ["Identify the number, portfolio owner, registration path and operator access.", "Confirm the selected provider’s genuine identity, number and verification requirements.", "Agree the inbox, integrations, data access and backup/retention scope.", "Configure an authenticated application and status endpoint in an authorized test environment.", "Prepare permitted recipients, message purposes and approved templates where required.", "Verify inbound routing, send failure, delivery evidence and manual escalation before launch."], links: [policyLink] },
    { id: "cloud-messages", heading: "Match message purpose, format and permission", paragraphs: ["Text, media, interactive choices, templates and multi-step forms can serve different tasks. Start with the customer’s need: a final invoice, a delivery update, an authentication code or a support reply. A file format or an example wording does not prove template approval, category classification or support in your chosen version.", windowQualification, "Keep marketing separate from transactional and authentication traffic when preparing volumes. A promotional addition can change a message’s purpose; ask for the applicable classification instead of choosing the cheapest category. Check opt-in, opt-out handling and an escalation path before automating a customer conversation."], table: { caption: "Illustrative message tasks — confirm support and classification", headers: ["Task", "Information to validate", "Operational check"], rows: [["Invoice/document", "Final version and intended recipient", "Attachment availability and delivery outcome"], ["Order update", "Correct order and non-promotional purpose", "Customer mapping and exception routing"], ["Authentication code", "Intended verification flow", "Expiry/security design and approved template"], ["Interactive enquiry", "Supported format/API version", "Fallback when the choice is unavailable"], ["Support reply", "Customer’s question and reply window", "Clear human escalation"]] } },
    { id: "cloud-delivery", heading: "Track accepted, delivered, failed and unknown separately", paragraphs: ["Store a business reference alongside each send request. An acknowledgement can identify a request for later tracking; it does not prove that the person received or read the message. Delivery updates and the applicable billing record answer different questions.", "A missing callback is an investigation state. Check endpoint availability, message references and provider status before retrying; do not infer zero cost or automatically duplicate every uncertain send. Decide what can be retried safely and what needs an operator.", "The example below is an invented local record shape, not a provider response schema or a live request. No customer number, credential or functioning endpoint is supplied."], code: { caption: "Synthetic reconciliation record — offline illustration", text: '{\n  "businessReference": "DEMO-INVOICE-001",\n  "requestState": "accepted",\n  "deliveryState": "unknown",\n  "billingState": "unresolved",\n  "nextAction": "inspect status before retry"\n}' }, steps: ["Record the request and business reference without exposing secrets in logs.", "Match delivery/failure events to the right reference and customer.", "Investigate missing or conflicting evidence before a duplicate send.", "Reconcile applicable charges and exceptions with the invoice.", "Give an operator a visible queue for unresolved cases."] },
    { id: "guide-billing-conditions", heading: "Message billing and platform costs", paragraphs: billingParagraphs, links: [priceLink, { label: "India pricing reasoning and synthetic arithmetic", href: "/blog/whatsapp-cloud-api-pricing-india-2026" }] },
    { id: "cloud-capacity", heading: "Plan capacity without promising a universal limit", paragraphs: [throughputQualification, "Capacity planning should include queue growth, recipient limits, template quality, webhook handling and the business team’s ability to resolve failures. A fast request rate is of little use if statuses are lost or customers cannot get help.", "Use a bounded pilot with your confirmed conditions. Observe actual completion and errors before increasing traffic. Do not use a template approval, business verification or version announcement as evidence that an automatic capacity upgrade occurred."] },
    { id: "cloud-measurement", heading: "Measure your own pilot before setting targets", paragraphs: ["Choose template and operating targets from your own workflow. There is no universal delivery, read, response or opt-out percentage established here.", "Define a denominator and period for each measure. For delivery, compare observed delivered outcomes with the sends in the same cohort and report unresolved cases separately. For response, distinguish customer replies from automated acknowledgements. For opt-outs, track whether the next send was prevented.", "Review template variables, document correctness and exceptions as well as throughput. Comparing equivalent periods is more informative than declaring success from one accepted request. Use synthetic test cases first, then obtain separate authority before any real customer pilot."] },
    { id: "cloud-next-step", heading: "Prepare a scoped implementation discussion", paragraphs: [organizationQualification, "Bring one workflow, its inputs, operator roles, number state, expected volumes and exception cases. Ask which parts are included and which require separate integration work. Agree the tests, cost scope and recovery plan before setting a launch date."], links: [{ label: "Discuss Cloud API setup", href: "/contact?source=cloud-api-guide" }, { label: "Read migration planning", href: "/blog/whatsapp-web-6-hour-logout-unofficial-api-migration-guide" }, ...planners] },
  ],
  faqs: [{ question: "Does an accepted request mean a message was delivered or billed?", answer: pricingFAQs[2].answer }, { question: "Must I delete my existing Business App account?", answer: migrationQualification }, { question: "Are all messages in a reply window free?", answer: pricingFAQs[3].answer }, { question: "How long does onboarding take?", answer: onboardingQualification }, { question: "Does this page test my account or send a message?", answer: "No. It is a reading guide with illustrative records. Account access, registration, approval and real-message testing require a separate supported plan and authorization." }],
};

export const migrationGuide: BillingGuide = {
  slug: "whatsapp-web-6-hour-logout-unofficial-api-migration-guide",
  cover: { src: "/images/blog/whatsapp-web-6-hour-logout-unofficial-api-migration-guide/cover-refined-2026-10-watermarked.webp", width: 1200, height: 630, alt: "Blank browser laptop connected to workflow cards beside an assessment folder", caption: "Illustration: inventory browser-session dependencies before assessing a supported migration path." },
  title: "WhatsApp Web Sessions and Official API Migration: A Planning Guide",
  description: "Assess browser-session dependencies, standard and eligible hybrid paths, genuine onboarding information, backup, recovery and costs before migrating a number.",
  intro: "If a business workflow relies on a linked browser session, understand that dependency before changing it. An official API implementation can use a different connection model, but registration, eligibility, permissions, delivery and recovery still need a plan. Neither a logout headline nor a provider’s sales claim proves a safe migration for your number.",
  sections: [
    { id: "migration-history", heading: "Read the six-hour announcement as dated context", paragraphs: ["PIB’s 1 December 2025 release reports DoT directions issued on 28 November 2025 for specified app-based communication services using Indian mobile numbers. It describes periodic web-service logout no later than six hours, re-linking and a 90-day implementation requirement.", "That historical announcement does not establish the behavior of every integration today, a timer starting at every QR scan, a universal exemption for Cloud API or a verified deadline for your account. This guide does not certify current enforcement or legal compliance. Check the current applicable provider and regulatory position before relying on a specific cutoff.", "The practical migration question is narrower: does your current automation depend on a browser-linked session, how do you notice a disconnect, and what stops or recovers safely? Keep the observation separate from the rule’s legal scope."], links: [{ label: `PIB announcement of 1 December 2025 — opened ${billingEvidenceDate}`, href: migrationHistoryURL }] },
    { id: "migration-session-dependency", heading: "Inventory the existing connection and its failures", paragraphs: ["Some unofficial integrations imitate a web client; others may have different mechanisms. Record the actual software, connection method, account owner and support arrangement rather than asserting that all such APIs fail in the same way.", "An interrupted session can leave payment reminders, invoice messages or support routing incomplete. It does not tell you whether every queued message failed, whether one was already delivered or whether a retry would duplicate it. Preserve business references and investigate actual status.", "Do not plan a keep-alive workaround or an undocumented bypass as a business reliability strategy. Evaluate a permitted, supported path and an operator fallback. Equally, an official API label is not a promise of uninterrupted service or immunity from restrictions."], steps: ["List each ERP/CRM/send/support workflow and its connection dependency.", "Identify queued, accepted, delivered, failed and unknown records separately.", "Agree how operators learn about a disconnect and pause affected automation.", "Keep a recoverable export and a manual path for urgent work."] },
    { id: "guide-platform-conditions", heading: "Assess standard and eligible hybrid paths separately", paragraphs: [migrationQualification, compatibilityQualification, historyQualification], table: accountTable, links: [{ label: "Account-specific coexistence assessment", href: "/whatsapp-coexistence" }] },
    { id: "migration-standard", heading: "Plan the standard API interface and number transition", paragraphs: ["A standard path means your team needs an API application and a chosen inbox or integration. Document where staff will answer, which permissions they receive and how attachments, assignment and escalation will work. Do not assume a particular provider portal is the only possible interface.", "Confirm the transition steps for an existing app or API number before unregistering anything. Display-name treatment, business verification and badge approval are separate questions; a demonstration of a branded profile does not prove your account will receive that display.", "Choose a reversible sequence where the supported flow allows one. Agree how to stop the old automation, reconcile outstanding records and recover if registration or the new inbox is unavailable. Do not delete a working account based on this guide."], steps: ["Confirm current number state, ownership and supported registration path.", "Agree backup/retention and any supported import before a change.", "Prepare the new inbox, operator roles, templates and status handling.", "Reconcile and pause the old queue at the agreed cutover point.", "Validate the new path and document the recovery/escalation procedure."] },
    { id: "migration-hybrid", heading: "Check hybrid behavior without promising seamless history", paragraphs: ["A hybrid assessment is useful when staff need the Business App as well as API automation. Assess the exact number, country, app/API version and provider flow. Confirm how manual and automated replies are distinguished and how operators avoid duplicate answers.", "Ask which records, attachments and devices carry over, which remain in the app and what the integration actually stores. A connected account is not proof that every historical chat became CRM data. Confirm permission and retention for the records you intend to copy.", "Phone changes, inactivity, disconnects and app updates can affect operations. Obtain the supported connection and recovery instructions for your account; this page establishes no fixed inactivity period, automatic reconnection or permanent avoidance of re-authentication."], links: [{ label: "Hybrid account questions", href: "/whatsapp-coexistence#coexistence-conditions" }] },
    { id: "migration-identity", heading: "Provide genuine business information and a real website when requested", paragraphs: ["The Business Messaging Policy calls for accurate business identity and customer support contact information. Use details that describe the actual operator and the service customers receive. A name, brand affiliation or verification document must not be invented to obtain approval.", "If the selected verification flow requests a website, use a functioning site that genuinely describes your business and check the requested ownership/details with the provider. Do not submit a dummy website or fabricated evidence to pass review. The detailed verification documentation could not be retrieved for this check, so this page does not assert a universal list of required documents or domains.", "Business-profile contact options, business verification and the privacy duties relevant to your own operation are distinct. Whats91’s operator details and legal documents do not become universal customer website requirements. Confirm what applies to your business and onboarding flow.", onboardingQualification], links: [policyLink] },
    { id: "migration-message-window", heading: "Prepare templates, permission and a human fallback", paragraphs: [windowQualification, "Inventory first-contact, follow-up and support messages separately. Record the intended purpose, recipient permission and template status for the actual flow. Approval of a template is not permission to send it to every stored contact.", "Keep an operator route for invalid customer mappings, disputed balances, failed media or unresolved delivery. A change in connection model should not remove the customer’s way to get help. Review opt-outs before moving any contact list."] },
    { id: "migration-buying-conditions", heading: "Confirm migration and subscription costs", paragraphs: [...billingParagraphs, "Separate number/onboarding work, ERP integration, inbox/subscription, message charges and invoice treatment. Confirm duration, renewal and cancellation in writing. There is no confirmed two-year or three-year saving, price lock or universal provider markup here."], links: [priceLink, { label: "Detailed India budgeting guide", href: "/blog/whatsapp-cloud-api-pricing-india-2026" }, ...planners] },
    { id: "migration-cutover", heading: "Use evidence-based readiness stages", image: { src: "/images/blog/whatsapp-web-6-hour-logout-unofficial-api-migration-guide/cutover-checks-refined-2026-10-watermarked.webp", width: 1440, height: 810, alt: "Abstract assessment, preparation, rehearsal and pilot cards with a pause and recovery branch", caption: "Illustration: rehearse and set stop and recovery criteria before any separately authorized cutover." }, paragraphs: ["Readiness is a sequence of checks, not a fixed go-live promise. Agree who can approve each stage and which failure prevents the next one. Preserve an operator-controlled pause so a broken mapping or uncertain delivery state does not trigger more sends.", "A synthetic rehearsal can exercise state handling and reconciliation without accessing customer accounts. A real pilot needs separate authority, confirmed recipients and a supported account. Do not treat a website contact enquiry as authorization to register a number or send messages."], table: { caption: "Migration readiness and stop conditions", headers: ["Stage", "Evidence to gather", "Stop if"], rows: [["Assess", "Number state, access and supported path", "Ownership or eligibility is unresolved"], ["Prepare", "Backups, interface, templates and mapping", "Required records cannot be recovered"], ["Rehearse", "Synthetic failures, duplicates and escalation", "Unknown states produce blind retries"], ["Pilot", "Separately authorized account/customer test", "Delivery, billing or recovery is unresolved"], ["Cut over", "Queue reconciliation and named operators", "Old and new systems can duplicate sends"]] } },
    { id: "migration-next-step", heading: "Bring one workflow and its exceptions", paragraphs: [organizationQualification, "For a migration discussion, bring the connection method, number state, operator needs, history scope and outstanding queue. Ask for a written path, cost scope and recovery plan. A supported migration can be evaluated without promising that every old workflow, mobile feature or stored conversation will transfer."], links: [{ label: "Discuss migration planning", href: "/contact?source=migration-guide" }, { label: "Request a scoped demo", href: "/contact?source=migration-guide&subject=Migration%20demo" }, { label: "Cloud API setup and delivery guide", href: "/blog/whatsapp-cloud-api-complete-guide-2026" }] },
  ],
  faqs: [{ question: "Does the December 2025 announcement prove my integration disconnects today?", answer: "No. The announcement is dated regulatory context. Confirm the current applicable rules and observe your actual integration; this guide does not establish account enforcement, a universal QR timer or a Cloud API exemption." }, { question: "Can I keep the Business App when migrating?", answer: compatibilityQualification + " " + migrationQualification }, { question: "Will my history and media all transfer?", answer: historyQualification }, { question: "Can I use a placeholder website to pass verification?", answer: "Use genuine business information and a real business website if the selected flow requests one. Do not fabricate evidence. Confirm the exact verification requirements for your portfolio/provider rather than assuming a universal website checklist." }, { question: "Does migration guarantee a badge, uptime or a multi-year saving?", answer: "No. Confirm display-name/badge eligibility, connection/recovery behavior and commercial terms separately. An official API path does not establish a numerical SLA or a current discount." }],
};

export const indiaPricingGuide: BillingGuide = {
  cover: { src: "/images/blog/whatsapp-cloud-api-pricing-india-2026/cover-refined-2026-10-watermarked.webp", width: 1200, height: 630, alt: "Three separate paper file boxes for messaging usage, platform terms and invoice evidence on a budgeting desk", caption: "Illustration: message charges, platform terms and invoice treatment are separate inputs to a responsible budget." },
  slug: "whatsapp-cloud-api-pricing-india-2026", faqId: "guide-questions", relatedId: "guide-related",
  title: "WhatsApp Cloud API Pricing India 2026: Budgeting and Billing Conditions",
  description: "Separate message charges, platform fees, setup and taxes. Check effective rate scope, billing evidence and written buying conditions before committing a budget.",
  intro: "Build a budget from the effective message rules and your written platform offer. Keep category volumes, billing currency and delivery evidence visible. This guide publishes the official INR schedule effective 1 October 2026, explains its allowances and tiers, and keeps an invented arithmetic exercise separately labelled. A Meta estimate is not a total payable quote.",
  sections: [
    { id: "guide-rate-scope", heading: "Start with the effective rate scope", paragraphs: [pricingQualification, "Keep the original rate-card currency and billing unit. An India INR rate cannot be relabelled as USD, GBP or another currency. A dated card does not establish the applicable price for a different period, and a list-rate sheet alone does not establish tiers, free allowances or account eligibility.", "Use the relevant pricing period for the messages you are budgeting. Keep evidence of the recipient market, account billing arrangement and applicable category. If the period crosses a change, split it into the supported periods rather than applying one rate to every day.", "The official October 2026 INR list-rate download matches the owner-supplied workbook byte for byte. The official INR tier workbook and current Meta policy pages were also checked on 29 September 2026. This dated schedule applies from 1 October 2026 at midnight in the Messaging account timezone; it is not the pre-October price."], table: { caption: `India list rates — INR per delivered message; ${metaPricingSchedule.effectiveLabel}`, headers: ["Category", "List rate"], rows: indiaRateRows }, links: [priceLink] },
    { id: "guide-categories", heading: "Plan categories separately", paragraphs: [tierPricingPolicy, internationalPricingPolicy,"Record marketing, utility, authentication and service volumes separately. Confirm classification and any authentication-international treatment before budgeting; an example template does not establish approval or a rate.", "Do not discount all traffic because total volume crossed a threshold. A supported utility schedule uses utility volume; authentication uses its own schedule. Each tier applies only to the messages in that tier. Marketing and free service traffic cannot unlock unrelated category tiers.", "If you are comparing providers, keep the same period, currency, delivered volume and category mix. Different inclusion assumptions can make two totals look comparable when they describe different services."] },
    { id: "guide-windows", heading: "Confirm allowances beside the excluded traffic", paragraphs: [windowQualification, servicePricingPolicy, utilityPricingPolicy, freeEntryPricingPolicy, "Use the effective Service allowance and confirmed free-entry conditions below. Utility deliveries inside the 24-hour customer-service window are chargeable from 1 October 2026 unless a qualifying free-entry window exempts them.", "Record why a cohort was excluded, which period it covers and what evidence establishes its conditions. Keep unresolved traffic visible. Message-format permission, business verification and a reply-window timestamp answer different questions from invoice treatment."], links: [priceLink] },
    { id: "guide-synthetic-model", heading: "Work a marginal-tier example without treating it as a quote", paragraphs: ["The following INR rates are invented solely to explain arithmetic. They are not current or historical Meta rates, Whats91 fees or an offer. The example assumes eligible delivered volumes in one synthetic billing period; it deliberately gives service a zero rate by fixture assumption, not by a permanent free-service claim.", "At 1,200 utility messages, the first 1,000 use ₹0.10 and only the next 200 use ₹0.08. Repricing all 1,200 at the cheaper rate would produce ₹96.00 and undercount this example by ₹20.00. Adding marketing or service volume does not change that utility calculation.", "Authentication has its own invented threshold and rates. Calculate each category from its own schedule before rounding the subtotal. Keep platform, setup and tax unavailable if their terms are unknown; an available Meta-model subtotal is not a total payable amount."], table: { caption: `Synthetic delivered-message arithmetic — INR, per message; no real pricing period or account approval; source model checked ${billingEvidenceDate}`, headers: ["Category", "Synthetic volume", "Invented marginal schedule", "Rounded amount"], rows: syntheticBillingRows.map(row => [...row]) }, code: { caption: "Synthetic calculation — platform, setup and tax held separately", text: syntheticBillingCode }, note: "The invented example Meta-model subtotal is ₹2,366.40. The real website calculators use the separate official INR schedule effective 1 October 2026. Do not copy these invented exercise rates into a budget.", links: [priceLink] },
    { id: "guide-cost-components", heading: "Separate delivery, platform and tax amounts", paragraphs: [noMarkupPolicy, commercialQualification, "Budget Meta delivery charges by effective card, market, currency, category and tier. The listed Whats91 plan prices, monthly setup fees, annual setup inclusion and 18% GST calculation are on /plans. Confirm feature scope, renewal and any integration work separately.", "The platform first-payment amount is not a combined Meta invoice. Confirm final invoice treatment and input-tax-credit eligibility; do not treat unknown delivery, integration or add-on charges as zero.", "A provider comparison needs that provider’s dated written terms. Confirm tax inclusion and whether setup recurs at renewal; no multi-year discount is inferred from this message rate card."], table: { caption: "Budget lines and required evidence", headers: ["Line", "Basis", "If missing"], rows: [["Meta", "Effective delivered-message scope", "Amount unresolved/unavailable"], ["Platform", "Listed Whats91 plan and cycle on /plans", "Choose a plan and cycle"], ["Setup/integration", "Listed setup plus separately agreed integration", "Integration quote needed"], ["Tax", "18% GST on listed platform/setup; confirm other invoice treatment", "Confirm any other tax"], ["Total payable", "All supported components", "Do not substitute zero"]] } },
    { id: "guide-reconciliation", heading: "Accepted, delivered and unresolved are different states", image: { src: "/images/blog/whatsapp-cloud-api-pricing-india-2026/reconciliation-refined-2026-10-watermarked.webp", width: 1440, height: 810, alt: "Three separate columns of request, delivery and billing evidence cards with an unmatched card in an amber tray", caption: "Illustration: match request, delivery and billing evidence; keep unmatched records unresolved rather than assigning a guessed amount." }, paragraphs: [pricingFAQs[2].answer, "For a monthly budget, use one pricing period and original currency, document confirmed exclusions and round money consistently. Keep platform and tax lines separate from the Meta subtotal.", "Consider three reconciliation cases. An accepted request with no delivery evidence is unresolved. A matched delivered event can be evaluated against the effective scope; it is not by itself a final invoice. A failed record must be reconciled with the provider’s billing evidence rather than silently counted as delivered. Never turn a missing callback into a zero-cost record.", "Compare message IDs, cohort dates and categories, then investigate duplicates and late statuses. Preserve an exception list so the accounts team can distinguish an estimate from a billed amount. The website does not inspect an account invoice or resolve those exceptions for you."], table: { caption: "Billing evidence states — illustrative, no live invoice", headers: ["Request", "Delivery evidence", "Billing treatment"], rows: [["Accepted", "Missing", "Unresolved; inspect before retry"], ["Accepted", "Delivered", "Evaluate effective conditions and reconcile invoice"], ["Accepted", "Failed", "Reconcile failure with billing record"], ["Unknown", "Conflicting or unmatched", "Investigate reference; no guessed amount"]] } },
    { id: "guide-next-step", heading: "Prepare the inputs before committing a budget", paragraphs: ["The two website calculators share the same official dated schedule and marginal arithmetic. Enter delivered quantities, remaining Service allowance, prior paid tier counts and confirmed free-entry exclusions. They estimate Meta delivery charges without Whats91 markup; neither inspects an invoice nor takes payment.", "Bring category counts, intended market, original billing currency, pricing period, exclusions and the written platform scope. Ask for separate setup, renewal and invoice/tax treatment. If any material input is missing, retain an unavailable total and resolve that line before buying."], steps: ["Choose the relevant period and account billing currency.", "Separate delivered category counts from accepted or unresolved traffic.", "Confirm each allowance/tier and preserve its supporting conditions.", "Obtain written platform/setup/renewal terms and applicable invoice treatment.", "Reconcile the resulting estimate with actual delivery and billing records."], links: planners },
  ],
  faqs: pricingFAQs,
};
export const billingGuides = [cloudGuide, migrationGuide, indiaPricingGuide];
